9 c 214567 développement
KilianL55/sio-skills pull request #20
Opened 2022-11-20 14:37 UTC by KilianL55

Compétences évaluées :

- C 2.1.(4.5.6.7)] Développement
- [C 2.1.10] Conception de documentation

@jcheron

2022-11-20 15:26 UTC, jcheron requested changes
### Sur le fond
Pour l'accès aux données, il faudrait peut-être montrer une **Entity**, ça permettrait d'expliquer le principe.

Et le principe des Repositories serait à expliquer également :
- Les méthodes fournies par défaut par l'interface ```CrudRepository``` ou ```JpaRepository```
- La possibilité d'y ajouter ses propres méthodes 
### Sur la forme
Les fichiers md ne sont pas présentés (ils sont bruts).
Il faut utiliser les possibilités de présentation du MarkDown (titre, listes, tableau, liens, images, icônes...)

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +Durant le projet E-Music j’ai utilisé le framework spring boot.
Evitez de raconter...

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +Utilisation de composants d’accès aux données
Faire le lien vers les issues correspondantes, et utiliser une liste

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +```
Mettre 
```
```java
```
pour avoir la coloration syntaxique

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +Pour mettre à jour les données de l’utilisateur connecté, on récupère cette utilisateur grâce
Un utilisateur => cet utilisateur

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +Pour plus d’exemple consulté le repository Github du projet e-music :
Pour un exmple plus complet, vous pouvez conculter le repository...
qui n'est pas accesible je crois (private ?)

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +
Supprimez les sauts de ligne inutiles

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +
Si vous mettez un exmple de code, il faut qu'il soit exemplaire.
Celui là ne l'est pas trop, avec toutes ces affectations
Ce serait mieux d'ajouter une méthode copyFrom dans la classe ```Responsable```

```java
class DummyBean {
  private String member1;
  private String member2;

  public void copyFrom(DummyBean another) {
    this.member1 = another.getMember1();
    this.member2 = another.getMember2();
  }
}
```
Et de l'appeler ensuite:
```java
resp.copyFrom(responsable);
```

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/[C 2.1.10] Conception de documentation.md
> +Durant j’ai été amené à générer la documentation du framework que l’entreprise utilise.
Durant...
il manque des mots

2022-11-20 15:26 UTC, jcheron commented on myDocuments/bloc2-slam/[C 2.1.10] Conception de documentation.md
> +
C'est un peu court comme explications
Vous ne dîtes rien de l'intérêt de documenter, de ce que vous avez documenté, de comment vous l'avez fait...

2022-11-20 15:30 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +Utilisation de composants d’accès aux données
- [**C 2.1.4** Exploitation des ressources du cadre applicatif (Framework)](https://github.com/KilianL55/sio-skills/issues/9)
- [**C 2.1.7** Utilisation de composants d'accès aux données](https://github.com/KilianL55/sio-skills/issues/9)

2022-11-20 15:31 UTC, jcheron commented on myDocuments/bloc2-slam/SIO Skills C 2.1.(4.5.6.7)] Développement (1).md
> +Pour plus d’exemple consulté le repository Github du projet e-music :
Ah non, c'est celui de Zaacom qui ne l'est pas

2022-11-21 09:13 UTC, KilianL55 commented
Pouvez vous vérifier les modifications @jcheron

2022-11-21 09:42 UTC, jcheron reviewed
Orthographe à vérifier + typos (lettres manquantes)
Sur le fond, c'est mieux

2022-11-21 13:27 UTC, jcheron reviewed
Ca reste un peu court sur la partie Mappage Objet/relationnel (via les annotations).

2022-11-21 13:28 UTC, jcheron approved these changes

2022-11-23 06:58 UTC, merged